apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: neurostore
resources:
  - namespace.yaml
  - control-plane-configmap.yaml
  - control-plane-secret.yaml
  - control-plane-pvc.yaml
  - control-plane-deployment.yaml
  - control-plane-service.yaml
  - control-plane-hpa.yaml
  - control-plane-networkpolicy.yaml
  - s3-gateway-configmap.yaml
  - s3-gateway-secret.yaml
  - s3-gateway-pvc.yaml
  - s3-gateway-deployment.yaml
  - s3-gateway-service.yaml
  - s3-gateway-hpa.yaml
  - s3-gateway-networkpolicy.yaml
  - ingress.yaml
