global:
  scrape_interval: 15s

scrape_configs:
  - job_name: control-plane
    static_configs:
      - targets: ["control-plane:8080"]
    metrics_path: /metrics

  - job_name: s3-gateway
    static_configs:
      - targets: ["s3-gateway:9009"]
    metrics_path: /metrics

  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
